### ISSUE TITLE
FeatureReq: Use GNU/Emacs NS port's `Info.plist` instead of the one shipped with Emacs Macport 

### ISSUE THREAD

**Issue by LdBeth** [railwaycat/homebrew-emacsmacport#120]
One thing worth to notice is Emacs Macport does not have the file icons like the official port's file icons support, I've tested overwrite the `Info.plist` under `Contents` of the Application Bundle and copy  `document.icns` to `Resources` and there is not much side effects.

<img width="794" alt="2017-10-29 9 31 25" src="https://user-images.githubusercontent.com/22933696/32154820-8ccaf88c-bcf0-11e7-9b9b-56e42631a82b.png">

To force recache the file icons on macOS (Mavericks or later), run `sudo /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user`. It might take a while.

**Comment by railwaycat** [comment]
Thanks for suggestion! I add a patch to adopt CFBundleDocumentTypes parts from NS port and an option to let user decide if using the `documents.icns` from NS port or not -- because it's not a "GNU head" one :) Changes checked in by https://github.com/railwaycat/homebrew-emacsmacport/commit/0542cb36178fc18a144fe7e13ee77b3b65601fec

I've sent this patch to upstream and let's see if Mr. Yamamoto want it in trunk or not.

**Comment by railwaycat** [comment]
This patch in emacs-26.1-rc1-mac-6.90 now.
