### ISSUE TITLE
emacs-26.1-rc1-mac-6.90 upgrade broken on 10.13

### ISSUE THREAD

**Issue by benswift** [railwaycat/homebrew-emacsmacport#129]
Just saw this error:

```
railwaycat/emacsmacport/emacs-mac emacs-25.3-mac-6.8 -> emacs-26.1-rc1-mac-6.90, youtube-dl 2018.04.09 -> 2018.04.16
==> Upgrading railwaycat/emacsmacport/emacs-mac --with-xml2 --with-spacemacs-icon --with-gnutls --with-imagemagick
Error: /usr/local/opt/gdbm not present or broken
Please reinstall gdbm. Sorry :(
```

brew config output:

```
brew config
HOMEBREW_VERSION: 1.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: e3cd9c972f55e9953830f98b4b64eb4ba10727b1
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3b9ce2d0d938c4104a8576b2ba815f22d8bb1325
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.1
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: N/A
```

**Comment by railwaycat** [comment]
hmm, I tried the following steps but not able to reproduce this issue, might missed some key parts?

1. `brew remove emacs-mac`, remove the current emacs-26.1-rc1-mac-6.90 I already installed
2. goto tap home and `git checkout 47047e1` to back to old version emacs-25.3-mac-6.8
3. `HOMEBREW_NO_AUTO_UPDATE=1 brew install emacs-mac ...` with your dependencies. 
4. `brew update` and `brew upgrade`, finished with success. 

or it might because of my brew are "too clean"? Have you tried `brew reinstall gdbm` as been suggested in the error message?

BTW, there always a solution to remove emacs-mac and install it again, since there's no any formula claims emacs-mac as a dependency.

**Comment by benswift** [comment]
Hey there

Thanks for looking into it.

I got it to work by trying to install, and then manually installing the "missing" things one by one. In the end, I had to `brew install`

- `gdbm`
- `sqlite`
- `python@2`

I'm happy to do it in the end, but I was wondering if they're required to build the project then perhaps they should be registered as build-time dependencies in homebrew?

**Comment by railwaycat** [comment]
This is interesting.. `emacs-mac` should only requires `autoconf` `automake` `pkg-config` and `texinfo`. I'm going to add `gnutls` as requires instead of optional, but it still nothing to do with `python@2`.

Actually I noticed my personal-using homebrew been introduced dependency of `python@2` by don't-know-which formula too. `gdbm` and `sqlite` are dependencies of `python@2`. This change happened recently.

**Comment by benswift** [comment]
Ok, sure. I didn't have the homebrew python2 installed because I use pyenv for managin my python stuff (and pipenv for package management).
