### ISSUE TITLE
Emacs 26 TCP Server Segfault

### ISSUE THREAD

**Issue by amnn** [railwaycat/homebrew-emacsmacport#138]
I recently updated Emacs and stumbled across a segfault when starting the emacs server, listening on TCP.

I'm now on `emacs-26.1-z-mac-7.0`, running on macOS 10.13.3, which I installed from homebrew using:

    brew update
    brew upgrade
    brew install --with-no-title-bars --with-spacemacs-icon emacs-mac

And then was able to repro the crash with a fairly small `init.el`:

    ;; init.el
    (setq server-use-tcp t) ;; *
    (server-start)

Which I then loaded using

    $ emacs -q --load init.el

Which fails with

    Fatal error 11: Segmentation faultfish: 'emacs -q --load /tmp/init.el' terminated by signal SIGSEGV (Address boundary error)

(which is really two messages, one from emacs and one from `fish`, my shell):

    Fatal error 11: Segmentation fault
    fish: 'emacs -q --load /tmp/init.el' terminated by signal SIGSEGV (Address boundary error)

This crash goes away if I comment out the line that I marked with `;; *`, which is what makes me think it has something to do with the TCP emacs server implementation.

**Comment by railwaycat** [comment]
>If you find a bug, then please try to reproduce it with some
  official builds such as X11 or NS (Cocoa).  If it turns out to be
  specific to the Mac port, then please report it to
  "mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp".  Otherwise (i.e.,
  it is also reproducible with official ones), report it using M-x
  report-emacs-bug *USING THE OFFICIAL BUILD* as such.

Please follow the instruction from Emacs Mac port developer YAMAMOTO Mitsuharu to report a bug, thanks!

**Comment by railwaycat** [comment]
BTW, I'm not sure if many people using emacs server on Mac port, since it lacks multi-tty support.
