### ISSUE TITLE
cask is built without metal support

### ISSUE THREAD

**Issue by kommen** [railwaycat/homebrew-emacsmacport#155]
The binary installed via `brew cask install emacs-mac-spacemacs-icon` lacks `emacs-mac`'s Metal support.

This can be easily verified via `otool -L Emacs.app/Contents/MacOS/Emacs`. The output should include `Metal.framework`. Another factor to verify this is the presence of `metal-device-name` in `(frame-monitor-attributes)`.

Building from source with `brew install emacs-mac` did build the binary with metal support as expected (the flag is on by default since `emacs-26.1-mac-7.4`: https://bitbucket.org/mituharu/emacs-mac/commits/a45e7595f9f7ceb6029ffa8d3340ebe9fc61fb7b)

FWIW: I see **huge** performance improvements on Retina Macs (15" MBP 2017) with Metal support enabled.

**Comment by railwaycat** [comment]
I believe this is because of casks (and the bundle on release page) before emacs-26.2-rc1-mac-7.5 built on 10.12 or earlier for the SDK compatible. 

Could you try upgrade your cask install or download the latest bundle with 10.14 in filename from release page https://github.com/railwaycat/homebrew-emacsmacport/releases and have another try?

**Comment by kommen** [comment]
I can confirm the latest bundle is now built to use emacs-mac's Metal support. Thanks!

**Comment by imkaihao** [comment]
> I can confirm the latest bundle is now built to use emacs-mac's Metal support. Thanks!

It seems like cask is now built without metal support again.

**Comment by railwaycat** [comment]
The upstream turns off metal support by default for a reason and marks this option as **experimental**. Here are the words from developer Mr Yamamoto:

>I originally turned on --with-mac-metal because it lowered the CPU load.
But I recently realized that it was caused by its lower frame rate.
M1 Mac accomplishes 60fps with or without Metal even with large frames, and the CPU load does not get an advantage from the use of Metal there.

On the build script side, there is no intentional change but only use the default value.
