### ISSUE TITLE
_continuousScroll is deprecated for NSEventTypeScrollWheel. Please use -hasPreciseScrollingDeltas.

### ISSUE THREAD

**Issue by llchen223** [railwaycat/homebrew-emacsmacport#156]
I just installed using Homebrew. 

Mac version:
```
MacOS High Sierra
Version 10.13.6 (17G2208)
MacBook Pro (15-inch, 2018)
Processor 2.9 GHz Intel Core i9
memory 16 GB 2400 MHz DDR4
Graphics Radeon Pro 560X 4096 MB
Intel UHD Graphics 630 1536 MB
```

This is the Emacs version:
`GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.6) of 2018-11-26`

I see this in the Console:
```
2018-11-26 11:26:02.262 Emacs[66491:665276] -_continuousScroll is deprecated for NSEventTypeScrollWheel. Please use -hasPreciseScrollingDeltas.
```

**Comment by railwaycat** [comment]
Hi, I would suggest you to follow the instruction below from [README-mac](https://bitbucket.org/mituharu/emacs-mac/src/85a43e7fcf736cf99a3d32bcf911dc72937abf66/README-mac?at=master&fileviewer=file-view-default) and report to upstream. Thanks!

>If you find a bug, then please try to reproduce it with some
  official builds such as X11 or NS (Cocoa).  If it turns out to be
  specific to the Mac port, then please report it to
  "mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp".  Otherwise (i.e.,
  it is also reproducible with official ones), report it using M-x
  report-emacs-bug *USING THE OFFICIAL BUILD* as such.
