### ISSUE TITLE
The candidate window of IME is not positioned well

### ISSUE THREAD

**Issue by panjie** [railwaycat/homebrew-emacsmacport#157]
When use Google Japanese Input inside a splitted window in this emacs port under macOS 10.14.1. The candidate window of the input method will go to the bottom of the emacs window, not beside the words I input.

**Comment by railwaycat** [comment]
Hi @panjie, I experience with this issue several times by macOS Pinyin IM too. It usually happens with first one or two words after switching from English to Pinyin IM, and back to normal if I continue my input.

I would suggest you to follow the instruction below from [README-mac](https://bitbucket.org/mituharu/emacs-mac/src/fd1cf1f3e7576ac3e5ffe6e2041fb881427d6acc/README-mac?at=master&fileviewer=file-view-default) to report issue to upstream. Thanks!

>If you find a bug, then please try to reproduce it with some
  official builds such as X11 or NS (Cocoa).  If it turns out to be
  specific to the Mac port, then please report it to
  "mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp".  Otherwise (i.e.,
  it is also reproducible with official ones), report it using M-x
  report-emacs-bug *USING THE OFFICIAL BUILD* as such.

**Comment by railwaycat** [comment]
emacs-26.2-mac-7.6 has a fix for the misplaced IME candidate window.

**Comment by panjie** [comment]
> emacs-26.2-mac-7.6 has a fix for the misplaced IME candidate window.

Thanks very much.

BTW, could you pls provide a compile option for support of xwidgets on macOS?
