### ISSUE TITLE
--with-no-title-bars not compatible with --HEAD

### ISSUE THREAD

**Issue by larstvei** [railwaycat/homebrew-emacsmacport#209]
Hi!

I would like to upgrade to emacs 27, but would also like to exclude the title bars (with `--with-no-title-bars`). When trying to install I get the following:

```
~ λ brew install emacs-mac --with-modules --with-no-title-bars --with-modern-icon --with-imagemagick --HEAD
Updating Homebrew...
Error: --with-no-title-bars patch not supported on --HEAD
```

Is there a way of getting both emacs 27 and no title bars?

**Comment by aiba** [comment]
This may be relevant: https://github.com/d12frosted/homebrew-emacs-plus/pull/160

**Comment by railwaycat** [comment]
I added this restriction because when using `--HEAD`, it's really out of control what kind of code base the formula will apply this patch to. 

Since the `work` branch of upstream get update not very frequently these days, it's reasonable to remove this restriction. Please feel free to open a new issue when you see patch or build failures, so I can know it's time to add a new warning or get the patch update to date. 

Restriction is removed by 2a3fa6f34d850f7dd8cddaf2990feb88bcbb27c8
