### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by vnckppl** [railwaycat/homebrew-emacsmacport#234]
I like this formula especially for the support for retina displays, but unfortunately, it is not very stable for me. This version of emacs crashes and / or hangs (beachball) several times per week. How can I find out what caused these issues so that I can send a bug report?

**Comment by railwaycat** [comment]
If you would like to file a bug report, please see the description in https://bitbucket.org/mituharu/emacs-mac/src/master/README-mac. I quote several lines here: 

>If you find a bug, then please try to reproduce it with some
  official builds such as X11 or NS (Cocoa).  If it turns out to be
  specific to the Mac port, then please report it to
  "mituharu+bug-gnu-emacs-mac@math.s.chiba-u.ac.jp".

Personally I will start on reproduce this issue on `emacs -q` without any configuration and check the core dump or crash reporter for details.

**Comment by jasonhemann** [comment]
@vnckppl I think I am encountering that same issue. As a work-around, at least in my case I can open a new frame C-x 5 2 and finish my work. As long as I don't switch to the original frame. 

`C-g`, no matter how  many times I press it, does nothing. The other recovery technique I saw mentioned is to send `SIGUSR2`/`USR2`. But that kills the process so it doesn't fix.

**Comment by vnckppl** [comment]
@jasonhemann Thanks! This is good to know. I'll try that next time.

**Comment by vnckppl** [comment]
I will close this because my original question about debugging has been answered, even though the issue with emacs-macport hanging has not been resolved yet.
