### ISSUE TITLE
Make build flags more discoverable

### ISSUE THREAD

**Issue by JasonMFry** [railwaycat/homebrew-emacsmacport#244]
I have spent probably 2 hours searching for `--with-no-title-bars` over the past 2 weeks. This is the result of bad documentation and naming the flag differently from emacs-plus.

## Problems

1. searching the official bitbucket repo returns no results
1. the flag is slightly different from emacs-plus, which afaik had this flag first
1. using an incorrect flag doesn't show the list of available flags
1. nearly all internet search results were focused on natural title bar
1. I didn't even know there was a github repo since the official repo is bitbucket, but the solution was only available in the github repo.

## Solutions

1. Add info on this flag to the bitbucket repo readme.
2. Consider renaming the flag to match emacs-plus. 
3. If the user passes an invalid flag, show the list of valid flags in console output.
4. Ensure the github and bitbucket repos contain the same information

**Comment by meain** [comment]
Just for reference, I think `brew info emacs-mac` shows all the flags.

**Comment by railwaycat** [comment]
Hi, sorry for your time. I'm the maintainer of this repo which includes Homebrew formulas and casks, but not the developer of Emacs-mac. I don't have the write permission of Bitbucket repo.

Just as @meain said above, description of all the options can be showed by `brew info emacs-mac` command. Those descriptions are not in the README page because a lot of users of this repo are cask users, pages of document explaining each formula options are useless for them but just disruption. I'm working on a restructure of README and Wiki to include more introduction and information, but still keep the README file simple and easy to read. 

For the option name between this repo and emacs-plus. `no-title-bars` patch for Emacs-mac and the similar patch for Emacs-plus, they are totally different patches. I don't think it's good that one should align the name of options with another. 

The handle of invalid options is basically by Homebrew itself, I'm afraid I can't do much in formula.

**Comment by railwaycat** [comment]
I added a wiki page includes all current options with description. I hope this could make things easier.

Currently it is a copy of `brew info emacs-mac` with options to two tables. I will keep filling in comments to it.
