### ISSUE TITLE
"open -a Emacs" with a new frame

### ISSUE THREAD

**Issue by akira-okumura** [railwaycat/homebrew-emacsmacport#249]
Hi all,

How do I automatically open a new frame when opening a file by "open -a Emacs"?

```
$ open -a Emacs foo.txt # foo.txt will be opened in a new frame (macOS window)
$ open -a Emacs bar.txt # will be opened in the above frame instead of creating a new frame
```

I use macOS 10.14.6 and railwaycat/emacsmacport/emacs-mac: stable emacs-27.2-mac-8.2, HEAD

**Comment by woolsweater** [comment]
The `open` command sends an Apple Event to Emacs, which is handled by the `mac-ae-open-documents` function in mac-win.el (found in Contents/Resources/lisp/term inside the application bundle). That function delegates to `dnd-open-local-file` whose documentation refers to `dnd-open-file-other-window`.

Setting `dnd-open-file-other-window` to `t` will create a new window for an opened document.

You may also need to set `pop-up-frames` to `t` or `graphic-only`. This controls Emacs' preference for using frames instead of windows across commands in general.

**Comment by akira-okumura** [comment]
Thank you very much. Honestly I already switched to another distribution, https://emacsformacosx.com , in which the default behavior is different. However, thanks to your kind explanation, I understand what parameter changes the behavior. If I need get back to Homebrew, I will follow your instruction.
