### ISSUE TITLE
MacPorts link?

### ISSUE THREAD

**Issue by ylluminate** [railwaycat/homebrew-emacsmacport#257]
Can we have a MacPorts link as well since some of us prefer to distance ourselves from the problems of Homebrew? Note: https://ports.macports.org/port/emacs-mac-app-devel/

It took a few minutes to isolate the name properly and having a de facto authority stating where the MacPorts reference and name is would be useful.

**Comment by jmhammond** [comment]
This `brew` recipe is simply a wrapper to download and install the code of Mitsuharu Yamamoto from https://bitbucket.org/mituharu/emacs-mac/overview. 

This project itself (including the patches) is open source [under a BSD license](https://github.com/railwaycat/homebrew-emacsmacport/blob/master/LICENSE.txt). The [license file](https://github.com/railwaycat/homebrew-emacsmacport/blob/master/LICENSE.txt )indicates you can redistribute the source so long as you include the license.

I'm not the developer, but I'd guessing if you wanted to setup and maintain a `macports` recipe, you certainly could.

**Comment by railwaycat** [comment]
Hi @ylluminate Sure I can include links to the MacPorts ports emacs-mac-app and emacs-mac-app-devel in the README file and formula info. I fully understand those people want an alternative of Homebrew. Since I'm only the maintainer of this Homebrew formula but not the developer of emac mac port or the MacPorts ports (I find this sentence is a bit hard to read:), those links will be just a useful reference but not de facto authority. 

@jmhammond yes, this repo is under BSD 2-Clause License.
