### ISSUE TITLE
natural-title-bar fails to install with --HEAD

### ISSUE THREAD

**Issue by ilyaw39** [railwaycat/homebrew-emacsmacport#281]
Installation fails when:

`brew install emacs-mac --HEAD --with-natural-title-bar`

with message:

```
==> Patching
==> Applying emacs-mac-title-bar-8.3.patch
patching file src/macappkit.m
Hunk #1 succeeded at 1935 (offset -327 lines).
Hunk #2 FAILED at 2539.
patch unexpectedly ends in middle of line
Hunk #3 FAILED at 6605.
2 out of 3 hunks FAILED -- saving rejects to file src/macappkit.m.rej
```

Installation succeeds when:

`brew install emacs-mac --with-natural-title-bar`

or:

`brew install emacs-mac --HEAD`

System: macOS 12.1 (M1 Pro)

**Comment by Yevgnen** [comment]
Same issue.

**Comment by railwaycat** [comment]
Thanks to let me know! It looks the patch no longer compatible with HEAD, this happens when HEAD changed a lot from release version.

**Comment by lochlainn** [comment]
I tried adjusting the patch, this one worked when I built it on my fork:
[titlebar-9.0.patch.txt](https://github.com/railwaycat/homebrew-emacsmacport/files/8429988/titlebar-9.0.patch.txt)

I would make a PR, but I'm not sure how to get the URL for the Formula when the patch doesn't exist in the repo yet.

**Comment by railwaycat** [comment]
Thank you @lochlainn! I just about to do the same thing.

Yes, this is tricky and has to be finished in 2 steps, since merge will always create new hash for commit.

You could try construct the URL in PR like

```
https://raw.githubusercontent.com/railwaycat/homebrew-emacsmacport/master/patches/emacs-mac-title-bar-9.0.patch
```

Where `master` be used instead of hash of commit, and `emacs-mac-title-bar-9.0.patch` is my suggestion for patch file name. Use `master` instead of hash fails the `brew audit` but we can fix it later. 

Or you can create the PR only with patch file under `patches` directory and I can put it into formula in later fix.

**Comment by lochlainn** [comment]
Cool! I tried what you suggested: https://github.com/railwaycat/homebrew-emacsmacport/pull/284
