### ISSUE TITLE
Don't add both directories to `locallisppath`

### ISSUE THREAD

**Issue by jasonhemann** [railwaycat/homebrew-emacsmacport#294]
[This script](https://github.com/railwaycat/homebrew-emacsmacport/blob/c7ea9380bc5a269d7163e2222ccaa75deecd7f3e/build-scripts/build-emacs.sh#L14) is adding *both* directories for locallisppath. But I believe that only one or the other is necessary, depending [if you are on MacOS Intel or Apple Silicon chip](https://docs.brew.sh/Installation)

Is my understanding correct? If so, I think it'd be better to add only whichever one is needed, depending on which platform is being deployed. That way you don't end up with unnecessary load-path bloat.

**Comment by railwaycat** [comment]
This change was introduced to fix #225. Because even on an Apple Silicon chip, people could install homebrew with Rosetta2 which will in `/usr/local/`.

At least it looks no harm to include an extra directory in `locallisppath`. This could be removed when less and less people on Rosetta2 homebrew or when Apple announces the retirement of Rosetta2.

**Comment by jasonhemann** [comment]
Oh, alright. Very good.
