### ISSUE TITLE
Feature request: maximal capability

### ISSUE THREAD

**Issue by dabrahams** [railwaycat/homebrew-emacsmacport#60]
If you build the binaries released here `--with-imagemagick --with-xml2` they will be more capable, I think?

**Comment by railwaycat** [comment]
Thanks for suggestion, I will try this on next release build.

**Comment by railwaycat** [comment]
`libxml2` already linked. But `ImageMagick` is a bit tough, OS X not comes with ImageMagick libraries, so it might better to install from Homebrew if needed and let `brew` controls the dependency?

Homebrew or MacPorts also the recommended way to install ImageMagick from its website.

**Comment by louy2** [comment]
It is possible to specify dependencies in cask too: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/depends_on.md

So maybe we can provide a maximally capable cask with all the dependencies listed. When I built mine I had to use `brew linkapp` which was deprecated because Spotlight doesn't pickup symlinks in `/Application`.

**Comment by railwaycat** [comment]
Sounds a good way. Thanks @louy2!

**Comment by railwaycat** [comment]
The app bundle now self-contains most of the libraries it depends on. I will close this issue since it's a long time.
