### ISSUE TITLE
Add flag to use the official icon

### ISSUE THREAD

**Issue by vemv** [railwaycat/homebrew-emacsmacport#97]
The release `*-official-icon` is great, but that does not include --with-no-title-bars.

The most flexible approach (rather than releasing many binaries) would be to implement a `--official-icon` flag.

WDYT?

Cheers - Victor

**Comment by railwaycat** [comment]
For `--with-no-title-bars`, a better way I realized is to modify the patch a bit to disable the feature by default (when build with the patch) and let user to enable it with configuration file. In that way I can include both patches in binary build and release with them, but let users to choose when to use the features.

I'm not sure if I fully understand your idea about `--official-icon` flag. If you mean to release just one bundle but with extra flags to modify icon file, I'm afraid I can't do that, because bundles are signed, any changes of files inside bundle will fail the signature.

**Comment by vemv** [comment]
Hi!

> a better way I realized is to modify the patch a bit to disable the feature by default (when build with the patch) and let user to enable it with configuration file.

Sounds good to me!

> I'm not sure if I fully understand your idea about --official-icon flag. If you mean to release just one bundle but with extra flags to modify icon file, I'm afraid I can't do that, because bundles are signed, any changes of files inside bundle will fail the signature.

I see. As long as I get official icon and no-title-bar, any implementation is ok to me! Whether it's a flag, or a different brew formula name (e.g. `brew install emacs-mac-official-icon`)

Cheers - Victor

**Comment by vemv** [comment]
Any chance of having this one?

I find it slightly irritating to have a gnu as part of my daily toolchain.

Thanks - Victor
